# Generated by Django 5.2.15 on 2026-06-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='exprience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='requried_skills',
            new_name='required_skills',
        ),
    ]
