# Generated by Django 5.2.15 on 2026-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_candidateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
