# Generated by Django 5.2.15 on 2026-06-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_candidate_processing_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
